# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

on:
  push:
    branches: [ "main" ]

jobs:
  CI: # name of the service we have given
    runs-on: ubuntu-latest
    steps:

    - name: Pull my code from github repo
      uses: actions/checkout@v4

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Creating docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/awsfirst .

    - name: Push the docker image to docker hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/awsfirst
      

    